#ifndef UI_SPRITES_HH_
#define UI_SPRITES_HH_

#include <cstdint>

#include "canvas.hh"

// Pre-baked 1-bit and 2-bit sprites for the Winglet map UI's fixed-shape
// assets, so they are blitted each frame instead of re-rasterized (no per-frame
// annulus sqrtf / gear-tooth trig / 9x halo polygon fills). The sprite bytes
// live in ui_sprites_data.cpp (generated by tools/gen_ui_sprites.py) and match
// the live primitives in ui_primitives.cpp / map_screen.cpp pixel-for-pixel.

namespace winglet_ui {

// 1 bit/pixel, MSB-first, ceil(w/8) bytes/row. A set bit = ink; clear =
// transparent (the sprite draws nothing there, leaving the background).
struct Sprite1bpp {
    const uint8_t* bits;
    uint16_t w, h;
};

// 2 bits/pixel, MSB-first, ceil(w*2/8) bytes/row. Per-pixel value:
//   0 = transparent, 1 = ink (drawn in `ink`), 2 = halo (drawn in `halo`).
// Lets ink + white halo travel together in a single blit.
struct Sprite2bpp {
    const uint8_t* bits;
    uint16_t w, h;
};

// ---- Blitters (defined in ui_primitives.cpp) ------------------------------
// Draw a 1bpp sprite with its top-left at (x,y); only set bits are painted in
// `ink` (transparent elsewhere).
void BlitSprite(Canvas& c, int x, int y, const Sprite1bpp& s, uint16_t ink);
// Draw a 2bpp sprite with its top-left at (x,y); value-1 pixels in `ink`,
// value-2 pixels in `halo`, value-0 skipped.
void BlitSprite2bpp(Canvas& c, int x, int y, const Sprite2bpp& s, uint16_t ink, uint16_t halo);

// ---- Baked sprite tables (defined in ui_sprites_data.cpp) ------------------
// Right-rail icons + battery frame (1bpp, ink-only — no halo, matching the
// live icons). Battery internal fill bar is still drawn live from pct.
extern const Sprite1bpp kZoomInSprite;
extern const Sprite1bpp kGearSprite;
extern const Sprite1bpp kZoomOutSprite;
extern const Sprite1bpp kBatteryFrameSprite;

// Scale bar (2bpp, haloed). Origin* give the offset from the sprite's top-left
// to the geometric (x1, bar_y) reference used by the live ScaleBarDraw, so the
// blit lands in the same place.
extern const Sprite2bpp kScaleBarSprite;
extern const int kScaleBarSpriteOriginX;
extern const int kScaleBarSpriteOriginY;

// 360 pre-rotated, pre-haloed aircraft arrows (2bpp), indexed by whole-degree
// heading [0,359]. Center* give the in-sprite center; blit at
// (contact_x - kArrowSpriteCenterX, contact_y - kArrowSpriteCenterY).
extern const Sprite2bpp kArrowSprites[360];
extern const int kArrowSpriteCenterX;
extern const int kArrowSpriteCenterY;

}  // namespace winglet_ui

#endif  // UI_SPRITES_HH_
