#ifndef PACKET_DECODER_HH_
#define PACKET_DECODER_HH_

#include "data_structures.hh"
#include "mode_s_packet.hh"
#include "settings.hh"

class ModeSPacketDecoder {
   public:
    static constexpr uint16_t kPacketQueueLen = 100;
    static constexpr uint16_t kDebugMessageQueueLen = 20;
    // Two demodulator state machines can occasionally catch the same transmission. Packets with identical contents
    // whose timestamps fall within this window are treated as duplicates. Distinct transmissions with identical
    // contents (e.g. bursts of interrogation replies) are spaced further apart than this.
    static constexpr uint64_t kDuplicatePacketWindow48MHzCounts = 48000;  // 1ms.
    static constexpr uint16_t kMaxNumSources = 4;

    struct PacketDecoderConfig {
        bool enable_1090_error_correction = true;
        bool max_1090_error_correction_num_bits = 1;
    };

    /**
     * Struct used to send Debug messages to the main core, since ModeSPacketDecoder is made to run on multiple cores.
     */
    struct DebugMessage {
        static const uint16_t kMessageMaxLen = 200;

        char message[kMessageMaxLen + 1] = {'\0'};
        SettingsManager::LogLevel log_level = SettingsManager::LogLevel::kInfo;
    };

    ModeSPacketDecoder(PacketDecoderConfig config_in) : config_(config_in) {};

    bool Init() { return true; }

    /**
     * Print all of the debug messages generated by UpdateDecoderLoop(). Should be run from the main loop to avoid
     * having debug messages from the decoder intermingled with debug messages from the main loop.
     */
    bool UpdateLogLoop();

    /**
     * Read in RawTransponderPackets, attempt checksum correction, and pass them to the output queue as
     * DecodedTransponderPackets.
     * @retval True if successful, false if something broke.
     */
    bool UpdateDecoderLoop();

    // Input queues.
    PFBQueue<RawModeSPacket> raw_mode_s_packet_in_queue = PFBQueue<RawModeSPacket>(
        {.buf_len_num_elements = kPacketQueueLen, .buffer = raw_mode_s_packet_in_queue_buffer_});

    // Output queues.
    // decoded_mode_s_packet_out_queue is written on Core 1 and read on Core 0 — must be thread-safe.
    // Define PFB_QUEUE_NO_THREAD_SAFETY to disable mutex locking (e.g. to diagnose deadlocks).
    PFBQueue<DecodedModeSPacket> decoded_mode_s_packet_out_queue = PFBQueue<DecodedModeSPacket>(
        {.buf_len_num_elements = kPacketQueueLen, .buffer = decoded_mode_s_packet_out_queue_buffer_,
#ifndef PFB_QUEUE_NO_THREAD_SAFETY
         .is_thread_safe = true
#endif
        });
    PFBQueue<uint16_t> decoded_mode_s_packet_bit_flip_locations_out_queue =
        PFBQueue<uint16_t>({.buf_len_num_elements = kPacketQueueLen,
                            .buffer = decoded_mode_s_packet_bit_flip_locations_out_queue_buffer_});
    PFBQueue<DebugMessage> debug_message_out_queue = PFBQueue<DebugMessage>({
        .buf_len_num_elements = kDebugMessageQueueLen,
        .buffer = debug_message_out_queue_buffer_,
    });

   private:
    bool PushPacketIfNotDuplicate(const DecodedModeSPacket &decoded_packet);

    PacketDecoderConfig config_;
    RawModeSPacket raw_mode_s_packet_in_queue_buffer_[kPacketQueueLen];
    DecodedModeSPacket decoded_mode_s_packet_out_queue_buffer_[kPacketQueueLen];
    uint16_t decoded_mode_s_packet_bit_flip_locations_out_queue_buffer_[kPacketQueueLen];
    DebugMessage debug_message_out_queue_buffer_[kDebugMessageQueueLen];

    // Last packet pushed from each source, used to drop the same message if it's caught by multiple state machines.
    struct LastPacket {
        uint32_t buffer[RawModeSPacket::kMaxPacketLenWords32] = {0};
        uint16_t buffer_len_bytes = 0;  // 0 = no packet recorded yet (never matches a real packet).
        uint64_t mlat_48mhz_64bit_counts = 0;
    };
    LastPacket last_packet_[kMaxNumSources];

    // Snapshot of whether debug messages would be printed, taken once per UpdateDecoderLoop() call.
    bool debug_enabled_ = false;

   public:
    bool decoded_mode_s_packet_out_queue_overflowed_ = false;
};

extern ModeSPacketDecoder decoder;

#endif /* PACKET_DECODER_HH_ */