#ifndef PACKET_DECODER_HH_
#define PACKET_DECODER_HH_

#include "data_structures.hh"
#include "mode_s_packet.hh"
#include "settings.hh"

class PacketDecoder {
   public:
    static constexpr uint16_t kPacketQueueLen = 100;
    static constexpr uint16_t kDebugMessageQueueLen = 20;
    static constexpr uint16_t kMinSameAircraftMessageIntervalMs =
        10;  // Minimum time between messages from the same aircraft.
    static constexpr uint16_t kMaxNumSources = 4;

    struct PacketDecoderConfig {
        bool enable_1090_error_correction = true;
        bool max_1090_error_correction_num_bits = 1;
    };

    /**
     * Struct used to send Debug messages to the main core, since PacketDecoder is made to run on multiple cores.
     */
    struct DebugMessage {
        static const uint16_t kMessageMaxLen = 200;

        char message[kMessageMaxLen + 1] = {'\0'};
        SettingsManager::LogLevel log_level = SettingsManager::LogLevel::kInfo;
    };

    PacketDecoder(PacketDecoderConfig config_in) : config_(config_in) {};

    bool Init() { return true; }

    /**
     * Print all of the debug messages generated by UpdateDecoderLoop(). Should be run from the main loop to avoid
     * having debug messages from the decoder intermingled with debug messages from the main loop.
     */
    bool UpdateLogLoop();

    /**
     * Read in RawTransponderPackets, attempt checksum correction, and pass them to the output queue as
     * DecodedTransponderPackets.
     * @retval True if successful, false if something broke.
     */
    bool UpdateDecoderLoop();

    // Input queues.
    PFBQueue<Raw1090Packet> raw_1090_packet_in_queue =
        PFBQueue<Raw1090Packet>({.buf_len_num_elements = kPacketQueueLen, .buffer = raw_1090_packet_in_queue_buffer_});

    // Output queues.
    PFBQueue<Decoded1090Packet> decoded_1090_packet_out_queue = PFBQueue<Decoded1090Packet>(
        {.buf_len_num_elements = kPacketQueueLen, .buffer = decoded_1090_packet_out_queue_buffer_});
    PFBQueue<uint16_t> decoded_1090_packet_bit_flip_locations_out_queue = PFBQueue<uint16_t>(
        {.buf_len_num_elements = kPacketQueueLen, .buffer = decoded_1090_packet_bit_flip_locations_out_queue_buffer_});
    PFBQueue<DebugMessage> debug_message_out_queue = PFBQueue<DebugMessage>({
        .buf_len_num_elements = kDebugMessageQueueLen,
        .buffer = debug_message_out_queue_buffer_,
    });

   private:
    bool PushPacketIfNotDuplicate(const Decoded1090Packet &decoded_packet);

    PacketDecoderConfig config_;
    Raw1090Packet raw_1090_packet_in_queue_buffer_[kPacketQueueLen];
    Decoded1090Packet decoded_1090_packet_out_queue_buffer_[kPacketQueueLen];
    uint16_t decoded_1090_packet_bit_flip_locations_out_queue_buffer_[kPacketQueueLen];
    DebugMessage debug_message_out_queue_buffer_[kDebugMessageQueueLen];

    // Arrays used for keeping track of last decoded message so that we don't re-process the same message if it's caught
    // by multiple state machines.
    uint32_t last_demod_icao_[kMaxNumSources] = {0, 0, 0, 0};
    uint32_t last_demod_timestamp_ms_[kMaxNumSources] = {0, 0, 0, 0};
};

extern PacketDecoder decoder;

#endif /* PACKET_DECODER_HH_ */