#!/bin/bash
# One-time developer environment setup
#
# Run from anywhere:
#     bash firmware/scripts/setup_dev.sh
#
# It will:
#   1. Initialize/update git submodules.
#   2. Install a native git pre-commit hook that runs the Settings/firmware
#      version sync check. No Python, pipx, or external framework required.
#
# This does NOT install the firmware build toolchain (Docker, ESP-IDF, TI SDK) —
# see firmware/README.md for those.

set -e

script_dir="$(cd "$(dirname "$0")" && pwd)"
root="$(git -C "$script_dir" rev-parse --show-toplevel)"
cd "$root"

echo "=== Initializing git submodules ==="
# Submodules are pinned with git@github.com: (SSH) URLs. Try SSH first; if it
# fails (no key configured), retry over HTTPS so a fresh clone still works
# without GitHub SSH access. The insteadOf rewrite is scoped to this one
# command and does not touch the user's git config.
if ! git submodule update --init --recursive; then
    echo "SSH submodule fetch failed; retrying over HTTPS..."
    git -c url."https://github.com/".insteadOf="git@github.com:" \
        submodule update --init --recursive
fi

echo "=== Installing git pre-commit hook ==="
# Write a tiny hook that shells out to check_version_sync.sh against the staged
# content (HEAD vs INDEX). Bypass a single commit with `git commit --no-verify`.
hook="$root/.git/hooks/pre-commit"
cat > "$hook" <<'EOF'
#!/bin/bash
# Auto-generated by firmware/scripts/setup_dev.sh — enforces the version-sync
# rule (see firmware/AGENTS.md). Bypass once with `git commit --no-verify`.
exec firmware/scripts/check_version_sync.sh HEAD INDEX
EOF
chmod +x "$hook"
echo "Installed $hook"

echo "=== Dev environment setup complete ==="
