version: '2.0'

networks:
  adsbnet:


services:

  tar1090:
    image: mikenye/tar1090:latest
    tty: true
    container_name: tar1090
    restart: always
    environment:
      - TZ=America/Los_Angeles
        #- BEASTHOST=192.168.1.55
        # - BEASTPORT=30004
        # NOTE: LAT/LON must be changed to your location for aircraft to show on the map!!
      - LAT=37.2833
      - LONG=-121.9355
    networks:
      - adsbnet
    ports:
      - 8078:80
      - 30004:30004
      - 30005:30005
    tmpfs:
      - /run:exec,size=64M
      - /var/log
