services:
  # Pico SDK container for compiling main firmware project.
  pico-docker:
    image: coolnamesalltaken/pico-docker:latest
    network_mode: host
    volumes:
      - ./pico:/adsbee/pico
      - ./common:/adsbee/common
      - ./modules:/adsbee/modules
      - ./esp:/adsbee/esp # Bind the ESP32 directory so that its firmware can be packaged into the RP2040 image.
      - ./ti:/adsbee/ti # Bind the TI directory so that its firmware can be packaged into the RP2040 image.
      - .vscode:/adsbee/.vscode

    command: tail -f /dev/null # keep the container running forever

  ti-lpf2:
    image: coolnamesalltaken/ti-lpf2:latest
    platform: "linux/amd64" # Make sure we run the AMD64 image so that installed utilities work.
    network_mode: host
    volumes:
      - ./ti:/adsbee/ti
      - ./common:/adsbee/common
      - ./modules:/adsbee/modules
      - .vscode:/adsbee/.vscode

    command: tail -f /dev/null # keep the container running forever
