services:
  # Pico SDK container for compiling main firmware project.
  pico-docker:
    image: coolnamesalltaken/pico-docker:latest
    network_mode: host
    volumes:
      - ./pico:/ads_bee/pico
      - ./common:/ads_bee/common
      - ./modules:/ads_bee/modules
      - ./esp:/ads_bee/esp # Bind the ESP32 directory so that its firmwawre can be packaged into the RP2040 image.
      - .vscode:/ads_bee/.vscode

    command: tail -f /dev/null # keep the container running forever
  # ESP IDF container for compiling custom ESP-AT firmware.
  # esp-docker:
  #   # image: espressif/idf:release-v4.4
  #   build: ./esp_at
  #   volumes:
  #     - .:/ads_bee # Bind mount ./esp_at as a folder for generated output from the configurator.
  #   entrypoint: /bin/bash -c "/project/entrypoint.sh && tail -f /dev/null"
