name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: coolnamesalltaken/pico-docker

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: create build directory
      run: mkdir -p $GITHUB_WORKSPACE/adsbee/firmware/pico/build
    - name: cd to build direcotry.
      run: cd $GITHUB_WORKSPACE/adsbee/firmware/pico/build
    - name: set build type to Test
      run: cmake -DCMAKE_BUILD_TYPE=Test ..
    - name: make
      run: make
    - name: ctest
      run: ctest
